/**
 * Generates the frontend's contract bindings from compiled artifacts and
 * deployment manifests.
 *
 *   npm run export:abi
 *
 * The previous frontend carried a hand-written ABI describing functions that
 * did not exist on any deployed contract (`joinGame`, `waterCrop`, `getPlot`,
 * `movePlayer`, a `plantCrop(plotId, seedType)` that took the wrong arguments)
 * and typed FarmLand as ERC-1155. Every call it made was guaranteed to fail.
 * Generating from artifacts makes that class of drift impossible: if a
 * function is not on the contract, it is not in the client.
 */
const fs = require("fs");
const path = require("path");
const { listDeployments } = require("./lib/deployments");

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts", "contracts");
const OUT_DIR = path.join(ROOT, "frontend", "lib", "generated");

const CONTRACTS = ["FarmToken", "FarmNFT", "FarmLand", "GameManager", "Marketplace"];

function loadAbi(name) {
  const file = path.join(ARTIFACTS, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(file)) {
    throw new Error(`Missing artifact for ${name}. Run: npx hardhat compile`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).abi;
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const abis = {};
  for (const name of CONTRACTS) {
    abis[name] = loadAbi(name);
  }

  const header = `// AUTO-GENERATED by scripts/export-abi.js - do not edit by hand.
// Regenerate with: npm run export:abi
/* eslint-disable */
`;

  fs.writeFileSync(
    path.join(OUT_DIR, "abis.ts"),
    `${header}
${CONTRACTS.map(
  (name) => `export const ${toConstName(name)}_ABI = ${JSON.stringify(abis[name])} as const;`
).join("\n\n")}
`
  );

  const deployments = listDeployments();
  const byChain = {};
  for (const d of deployments) {
    byChain[d.chainId] = {
      chainId: d.chainId,
      network: d.network,
      deployedAt: d.deployedAt,
      contracts: d.contracts,
      config: d.config,
    };
  }

  fs.writeFileSync(
    path.join(OUT_DIR, "deployments.ts"),
    `${header}
export interface DeploymentContracts {
  FarmToken: string
  FarmNFT: string
  FarmLand: string
  GameManager: string
  Marketplace: string
}

export interface Deployment {
  chainId: number
  network: string
  deployedAt: string
  contracts: DeploymentContracts
  config: {
    landMintPrice: string
    marketplaceFeeBps: number
    starterPackTokens: string
    seedTypeCount: number
    recipeCount: number
  }
}

export const DEPLOYMENTS: Record<number, Deployment> = ${JSON.stringify(byChain, null, 2)}

export const DEPLOYED_CHAIN_IDS = Object.keys(DEPLOYMENTS).map(Number)
`
  );

  console.log(`Wrote ${CONTRACTS.length} ABIs to ${path.relative(ROOT, OUT_DIR)}/abis.ts`);
  if (deployments.length === 0) {
    console.log("No deployment manifests found - deployments.ts is empty.");
    console.log("Run scripts/deploy.js against a network first.");
  } else {
    for (const d of deployments) {
      console.log(`  chain ${d.chainId} (${d.network}) -> ${Object.keys(d.contracts).length} addresses`);
    }
  }
}

function toConstName(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

main();
