import { DEPLOYMENTS, type Deployment } from './generated/deployments'

export interface ChainInfo {
  chainId: number
  name: string
  shortName: string
  rpcUrls: string[]
  blockExplorer: string | null
  nativeCurrency: { name: string; symbol: string; decimals: number }
  isTestnet: boolean
}

export const SEPOLIA: ChainInfo = {
  chainId: 11155111,
  name: 'Sepolia',
  shortName: 'Sepolia',
  rpcUrls: [
    'https://ethereum-sepolia-rpc.publicnode.com',
    'https://sepolia.drpc.org',
    'https://rpc.sepolia.org',
  ],
  blockExplorer: 'https://sepolia.etherscan.io',
  nativeCurrency: { name: 'Sepolia Ether', symbol: 'ETH', decimals: 18 },
  isTestnet: true,
}

export const HARDHAT: ChainInfo = {
  chainId: 31337,
  name: 'Hardhat Local',
  shortName: 'Localhost',
  rpcUrls: ['http://127.0.0.1:8545'],
  blockExplorer: null,
  nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  isTestnet: true,
}

export const SUPPORTED_CHAINS: Record<number, ChainInfo> = {
  [SEPOLIA.chainId]: SEPOLIA,
  [HARDHAT.chainId]: HARDHAT,
}

/**
 * The chain the app targets. Configurable so the same build can point at a
 * local node during development and Sepolia in production.
 */
export const TARGET_CHAIN_ID = Number(
  process.env.NEXT_PUBLIC_CHAIN_ID ?? SEPOLIA.chainId
)

export function getChainInfo(chainId: number): ChainInfo | null {
  return SUPPORTED_CHAINS[chainId] ?? null
}

export const TARGET_CHAIN: ChainInfo = getChainInfo(TARGET_CHAIN_ID) ?? SEPOLIA

/** RPC used for read-only calls before (or without) a wallet connection. */
export function getReadRpcUrl(chainId: number = TARGET_CHAIN_ID): string {
  const override = process.env.NEXT_PUBLIC_RPC_URL
  if (override) return override
  const info = getChainInfo(chainId)
  return info?.rpcUrls[0] ?? SEPOLIA.rpcUrls[0]
}

/**
 * Deployment manifest for a chain. Generated by `npm run export:abi` from the
 * artifacts written at deploy time, so addresses cannot drift from reality.
 */
export function getDeployment(chainId: number = TARGET_CHAIN_ID): Deployment | null {
  return DEPLOYMENTS[chainId] ?? null
}

export function isSupportedChain(chainId: number | null | undefined): boolean {
  if (chainId == null) return false
  return Boolean(SUPPORTED_CHAINS[chainId] && DEPLOYMENTS[chainId])
}

export function toHexChainId(chainId: number): string {
  return `0x${chainId.toString(16)}`
}

export function explorerTxUrl(hash: string, chainId: number = TARGET_CHAIN_ID): string | null {
  const info = getChainInfo(chainId)
  return info?.blockExplorer ? `${info.blockExplorer}/tx/${hash}` : null
}

export function explorerAddressUrl(address: string, chainId: number = TARGET_CHAIN_ID): string | null {
  const info = getChainInfo(chainId)
  return info?.blockExplorer ? `${info.blockExplorer}/address/${address}` : null
}
